#!/usr/bin/env python3
"""
postprocess_moc.py — 将 moc 原始输出转换为模块实现单元

策略：
  Qt3 moc 输出自带 include（<qmetaobject.h> 等），将其移到 GMF。
  Qt4 moc 输出无自包含 include，手动添加 <QObject> 到 GMF。

  .cppm 模块接口中 Qt 头文件位于模块修饰域（非 GMF），
  因此实现单元 GMF 的同名 include 不会冲突。
"""

import re

def detect_moc_version(raw_text):
    m = re.search(r'Qt Meta Object Compiler version (\d+)', raw_text)
    if m:
        ver = int(m.group(1))
        return "qt3" if ver < 40 else "qt4"
    if "#include <qmetaobject.h>" in raw_text:
        return "qt3"
    return "qt4"

def postprocess(raw_text, module_name, input_filename=None):
    lines = raw_text.splitlines()
    moc_version = detect_moc_version(raw_text)

    gmf_includes = []
    body = []
    in_header_comment = True

    for line in lines:
        s = line.strip()

        if in_header_comment:
            body.append(line)
            if s.endswith("*/"):
                in_header_comment = False
            continue

        # #error 关于 QObject include 检查 → 移除
        if s.startswith("#error") and ("doesn't include <QObject>" in s
                                        or "does not include <QObject>" in s):
            continue

        if s.startswith("#include"):
            inc_match = re.search(r'#include\s+["<]([^">]+)[">]', s)
            if inc_match:
                inc_path = inc_match.group(1)
                inc_basename = inc_path.split("/")[-1]
                is_input_inc = False

                if input_filename:
                    input_basename = input_filename.split("/")[-1]
                    if (inc_basename == input_basename or
                        inc_basename == input_basename.replace(".cppm", ".moc_input.h") or
                        inc_basename == input_basename.replace(".cppm", ".h")):
                        is_input_inc = True
                if ".moc_input." in inc_path:
                    is_input_inc = True

                if is_input_inc:
                    continue

                # Qt3: 移动自包含 include（qmetaobject.h 等）到 GMF
                if moc_version == "qt3":
                    gmf_includes.append(s)
                    continue

        body.append(line)

    result = []
    result.append(f"// Module-compatible moc output for module '{module_name}'")
    result.append(f"// Generated by postprocess_moc.py from: {moc_version} moc output")
    result.append("")

    result.append("module;")
    # 宏需要 GMF include 或手动定义
    if moc_version == "qt4":
        # 只包含 qobjectdefs.h ——不含 qstring.h，避免默认参数冲突
        result.append("#include <QtCore/qobjectdefs.h>")
    # strcmp 在 GMF 中用 #include <string.h> 提供（宏不能通过模块导入传播）
    result.append("#include <string.h>")
    result.append("#include <cassert>")
    result.append("#ifdef Q_ASSERT")
    result.append("#undef Q_ASSERT")
    result.append("#endif")
    result.append("#define Q_ASSERT(x) assert(x)")
    # QT_BEGIN_MOC_NAMESPACE 可能在 qglobal.h 中定义,
    # 但在某些环境下未定义，手动兜底
    result.append("#ifndef QT_BEGIN_MOC_NAMESPACE")
    result.append("#define QT_BEGIN_MOC_NAMESPACE")
    result.append("#define QT_END_MOC_NAMESPACE")
    result.append("#endif")
    for inc in gmf_includes:
        result.append(inc)
    result.append("")
    result.append(f"module {module_name};")
    result.append("")
    result.extend(body)

    return "\n".join(result)

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Postprocess moc output for modules")
    parser.add_argument("input", help="Raw moc output file")
    parser.add_argument("output", help="Output module implementation unit")
    parser.add_argument("--module", required=True, help="Module name")
    parser.add_argument("--input-file", help="Original input filename (for include removal)")
    args = parser.parse_args()

    with open(args.input, "r") as f:
        raw = f.read()

    result = postprocess(raw, args.module, input_filename=args.input_file)

    with open(args.output, "w") as f:
        f.write(result)
        f.write("\n")

if __name__ == "__main__":
    main()
